/*Магазин заколочек для волос. Hand-made аксессуары для волос продаются через интернет-магазин.*/
myshop=> create table product (
id bigint generated by default as identity,
category_id integer,
product_name varchar(80),
describe text,
price integer,
constraint product_id_pkey primary key (id),
constraint product_price_not_negative_check check (price > 0),
constraint product_fk_category_id foreign key (category_id) references product (id) on delete restrict);
CREATE TABLE

myshop=> create table users (
id bigint generated by default as identity,
users_name varchar (80),
users_age integer,
constraint users_id_pkey primary key (id)
);

myshop=> create table category ( 
id bigint generated by default as identity,
name text,
constraint category_id_pkey primary key (id)
);
CREATE TABLE

myshop=> create table cart (
id bigint generated by default as identity,
user_id bigint,
product_id bigint,
j);